server:
  port: 9527
hystrix:
  dashboard:
    proxy-stream-allow-list: "*"
spring:
  application:
    name: springcloud-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: zuul-9527 #定义eureka上描述信息
    prefer-ip-address: true
info:
  app.name: sun-springcloud
  company.name: sunmiao
zuul:
  routes:
    mydept.serviceId: springcloud-provider-dept
    mydept.path: /mydept/**
  ignored-services: springcloud-provider-dept #忽略，不能使用springcloud-provider-dept 访问
  prefix: /sun #设置公共前缀