server:
  port: 7001

#euteka配置
eureka:
  instance:
    hostname: localhost #eureka服务端的实例名称
  client:
    register-with-eureka: false #是否向eureka注册中心注册自己
    fetch-registry: false # 如果fetch-registry 为false 则表明自己是注册中心
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka